runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: MySQLdb
  version: "latest"
env_variables:
    CLOUDSQL_CONNECTION_NAME: your-connection-name
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: your-cloudsql-user-password